name: Check for errors

on:
  # super-linter doesn't work with multiple commits in a push but it does work in a pull request
  pull_request:

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
     
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Check for errors
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: .*src/.*
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GOOGLE_JAVA_FORMAT: false
  
