name: Compile mod

on: 
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java: [17]
        
        os: [ubuntu-latest]
        
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        
      - name: Set up jdk ${{matrix.java}}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
            
      - name: Make gradle wrapper executable if not running on Windows
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
        
      - name: Build
        run: ./gradlew build
          
      - name: Capture the build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only get artifacts from one os using one jdk
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: build/libs/
