name: Publish to modrinth

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Make gradle wrapper executable
      run: chmod +x ./gradlew
      
    - name: Build mod and publish to modrinth
      env: 
        MODRINTH_TOKEN: ${{secrets.MODRINTH_TOKEN}}
      run: ./gradlew modrinth
